name: Update GitHub Stats

# Trigger on manual dispatch or twice daily (9 AM and 5 PM Nepal Time)
on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: "15 3,11 * * *"  # 9:00 AM and 5:00 PM Nepal Time (UTC+5:45)

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache-deps.outputs.cache-hit }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: 'pip'

      - name: Cache Dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  generate-stats:
    name: Generate Statistics
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Restore Dependencies Cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Stats Image
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          # Check rate limit before running
          response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/rate_limit)
          core_remaining=$(echo $response | jq -r '.resources.core.remaining')
          graphql_remaining=$(echo $response | jq -r '.resources.graphql.remaining')
          search_remaining=$(echo $response | jq -r '.resources.search.remaining')

          echo "Rate Limits - Core: $core_remaining, GraphQL: $graphql_remaining, Search: $search_remaining"

          if [ $core_remaining -lt 50 ] || [ $graphql_remaining -lt 50 ] || [ $search_remaining -lt 50 ]; then
            echo "::warning::API rate limits are running low!"
          fi

          if [ $core_remaining -lt 1 ] || [ $graphql_remaining -lt 1 ] || [ $search_remaining -lt 1 ]; then
            echo "::error::Rate limits exceeded!"
            exit 1
          fi

          python scripts/stats_script.py
        continue-on-error: false

  update-repo:
    name: Update Repository
    needs: generate-stats
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Need previous commit for file removal

      - name: Check for Changes
        id: check-changes
        run: |
          if [[ -f "stats_image.png" ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and Push Updates
        if: steps.check-changes.outputs.changes == 'true'
        run: |
          git config --local user.name "GitHub Action Bot"
          git config --local user.email "action@github.com"

          # Remove old stats image if it exists in git
          git rm -f stats_image.png || true

          # Stage the new image
          git add stats_image.png

          # Get current date for commit message
          current_date=$(date +'%Y-%m-%d %H:%M:%S %Z')
          git commit -m "Update stats image for ${current_date}"

          # Force push to ensure clean update
          git push origin ${GITHUB_REF#refs/heads/} --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notify:
    name: Notification
    needs: [generate-stats, update-repo]
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Check Workflow Status
        if: ${{ contains(needs.*.result, 'failure') }}
        run: |
          echo "::error::Workflow failed! Please check the logs for more details."
          exit 1

